import { LightningElement, api } from 'lwc';
import getInsight from '@salesforce/apex/ClientInsightService.getInsight';

export default class ClientInsight extends LightningElement {
    @api recordId;

    // App Builder design attributes.
    @api cardTitle = 'Client Insight (AI)';
    @api defaultQuestion = 'Summarize this customer\'s overall engagement with us this quarter.';

    question = '';
    answer = '';
    usedLiveModel = false;
    isLoading = false;
    hasError = false;
    errorMessage = '';

    cannedPrompts = [
        'Summarize engagement this quarter',
        'What has this client purchased?',
        'Summarize recent support history'
    ];

    connectedCallback() {
        this.question = this.defaultQuestion;
    }

    handleQuestionChange(event) {
        this.question = event.target.value;
    }

    handleCannedPrompt(event) {
        this.question = event.currentTarget.dataset.prompt;
        this.handleAsk();
    }

    async handleAsk() {
        this.isLoading = true;
        this.hasError = false;
        this.answer = '';
        try {
            const result = await getInsight({
                recordId: this.recordId,
                question: this.question
            });
            this.answer = result.answer;
            this.usedLiveModel = result.usedLiveModel;
        } catch (error) {
            this.hasError = true;
            this.errorMessage =
                error?.body?.message || 'Unable to generate an insight right now.';
        } finally {
            this.isLoading = false;
        }
    }

    get hasAnswer() {
        return !this.isLoading && !this.hasError && this.answer;
    }

    get modelBadge() {
        return this.usedLiveModel ? 'Generated by live model' : 'Generated by grounded assistant';
    }
}
